application: planetpythonjapan
version: 1
runtime: python
api_version: 1

handlers:
- url: /planet/css
  static_dir: static/planet/css

- url: /planet/images
  static_dir: static/planet/images

- url: /planet/syncrss
  script: main.py
  login: admin

- url: /planet/admin/.*
  script: main.py
  login: required

- url: /.*
  script: main.py
