application: planetpythonjapan
version: 1
runtime: python
api_version: 1

handlers:
- url: /planet/css
  static_dir: static/planet/css

- url: /planet/images
  static_dir: static/planet/images

- url: /.*
  script: main.py
